# Generated by Django 4.0.5 on 2022-06-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
