# Generated by Django 4.0.5 on 2022-06-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_likes',
        ),
    ]
