# Generated by Django 4.0.4 on 2022-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
