# Generated by Django 4.0.4 on 2022-05-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_myuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
