# Generated by Django 4.0.4 on 2022-05-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_alter_myuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='users/default.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
